# Generated by Django 4.0.3 on 2022-03-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subcategories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='data_toggle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
