# Generated by Django 4.0.3 on 2022-03-26 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_filter_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='Product_Image/product')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('40000 TO 50000', '40000 TO 50000'), ('30000 TO 40000', '30000 TO 40000'), ('10000 TO 20000', '10000 TO 20000'), ('1000 TO 10000', '1000 TO 10000'), ('20000 TO 30000', '20000 TO 30000')], max_length=68),
        ),
    ]
