# Generated by Django 4.0.3 on 2022-03-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_filter_price_price_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('10000 TO 20000', '10000 TO 20000'), ('30000 TO 40000', '30000 TO 40000'), ('1000 TO 10000', '1000 TO 10000'), ('40000 TO 50000', '40000 TO 50000'), ('20000 TO 30000', '20000 TO 30000')], max_length=68),
        ),
    ]
