# Generated by Django 4.0.3 on 2022-03-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_contact_alter_filter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('1000 TO 10000', '1000 TO 10000'), ('20000 TO 30000', '20000 TO 30000'), ('40000 TO 50000', '40000 TO 50000'), ('10000 TO 20000', '10000 TO 20000'), ('30000 TO 40000', '30000 TO 40000')], max_length=68),
        ),
    ]
