# Generated by Django 4.0.3 on 2022-03-27 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_status_product_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('40000 TO 50000', '40000 TO 50000'), ('1000 TO 10000', '1000 TO 10000'), ('30000 TO 40000', '30000 TO 40000'), ('10000 TO 20000', '10000 TO 20000'), ('20000 TO 30000', '20000 TO 30000')], max_length=68),
        ),
        migrations.AddField(
            model_name='product',
            name='smallcategories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.smallcategories'),
        ),
    ]
