# Generated by Django 4.0.3 on 2022-03-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_smallcategories_alter_filter_price_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subcategories'),
        ),
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('30000 TO 40000', '30000 TO 40000'), ('20000 TO 30000', '20000 TO 30000'), ('40000 TO 50000', '40000 TO 50000'), ('10000 TO 20000', '10000 TO 20000'), ('1000 TO 10000', '1000 TO 10000')], max_length=68),
        ),
    ]
