# Generated by Django 4.0.3 on 2022-03-29 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_order_total_alter_filter_price_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('editor', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='Product_Image/blog')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('10000 TO 20000', '10000 TO 20000'), ('20000 TO 30000', '20000 TO 30000'), ('30000 TO 40000', '30000 TO 40000'), ('1000 TO 10000', '1000 TO 10000'), ('40000 TO 50000', '40000 TO 50000')], max_length=68),
        ),
    ]
